Repository GitHubExperts-LK/GitHubExperts-LK.github.io, pull requests merged in 2020-10, with the labels that each got.

#18 Explore button scroll effect function
  src/app/components/landing-page/landing-page.component.html
  src/app/components/landing-page/landing-page.component.ts
Labels: hacktoberfest, hacktoberfest-accepted

#24 Feature/emailjs
  package.json
  src/app/components/common/collaborators/collaborators.component.html
  src/app/components/common/contact/contact.component.html
  src/app/components/common/contact/contact.component.ts
  src/assets/images/logo-dark-cut.png
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 set subject name
  src/app/components/common/contact/contact.component.html
Labels: hacktoberfest-accepted
